name = "JosephsonLoops"
uuid = "fb07e101-5a60-4408-9312-698af44306dd"
version = "0.1.0"
authors = ["WilliamCam <78771433+WilliamCam@users.noreply.github.com>"]

[deps]
BifurcationKit = "0f109fa4-8a5d-4b75-95aa-f515264e7665"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
Nemo = "2edaba10-b0f1-5616-af89-8c11ac63239a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Profile = "9abbd945-dff8-562f-b5e8-e1ebf5ef1b79"
QuestBase = "7e80f742-43d6-403d-a9ea-981410111d43"
SymbolicUtils = "d1185830-fcd6-423d-90d6-eec64667417b"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"
SymbolicIndexingInterface = "2efcf032-c050-4f8e-a9bb-153293bab1f5"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
BifurcationKit = "0.5.2"
DataStructures = "0.19.1"
DifferentialEquations = "7.16.1"
LinearAlgebra = "1.12.0"
ModelingToolkit = "10.26.0"
Nemo = "0.52.3"
Plots = "1.41.1"
Profile = "1.11.0"
QuestBase = "0.3.4"
SymbolicUtils = "3.32.0"
Symbolics = "6.56.0"
SymbolicIndexingInterface = "0.3.46"
Statistics = "1.11.1"
